[package]
name = "tg-rcore-tutorial-ch1-T3L1"
description = "ch1-T3L1: Chapter 1 of rCore Tutorial: A minimal bare-metal application running in RISC-V S-mode."
version = "0.0.1-preview.1"
edition = "2024"
authors = ["Feiran Qin <qfr23@mails.tsinghua.edu.cn>"]
repository = "https://github.com/os-biglab/tg-rcore-tutorial-ch1-T3L1"
homepage = "https://github.com/os-biglab/tg-rcore-tutorial-ch1-T3L1/tree/test"
documentation = "https://github.com/os-biglab/tg-rcore-tutorial-ch1-T3L1/tree/test/docs"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai","ai4ose","kernel","learning","os","rcore", "tutorial", "no-std", "riscv", "bare-metal"]
categories = ["no-std", "embedded"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-sbi = { package = "tg-rcore-tutorial-sbi", version = "0.4.8", features = ["nobios"] }
tg-kernel-alloc = { package = "tg-rcore-tutorial-kernel-alloc", version = "0.4.5" }
virtio-drivers = { package = "virtio-drivers", version = "0.1.0" }